vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        img_pub:
            uri_prefix: /images/publications
            upload_destination: '%kernel.project_dir%/public/images/publications'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
