controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation


print:
  path: /produit/print
  controller: App\Controller\ProduitController::print
  methods: ['GET']