#index:
#    path: /
#    controller: App\Controller\DefaultController::index
dql:
    path: /dql
    controller: App\Controller\EventAdminController::dql
    # controller: App\Controller\ProduitController::dql
    methods: [POST]  